version: '3'
services:
  porter_DB:
    image: postgres:14
    restart: always
    ports:
      - "5447:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: porter_DB
    volumes:
      - .:/docker-entrypoint-initdb.d